baseURL = 'http://example.org/'
languageCode = 'ru-ru'
title = "Документация webTLO"
theme = "hugo-theme-relearn"
defaultContentLanguage = "ru"

[outputs]
home = [ "HTML", "RSS", "JSON"]

[params]
themeVariant = ["keepers-dark", "keepers-light"]
